name: Deploy FastAPI

on:
  push:
    branches: [ main ]  # 사용하는 브랜치명으로 변경

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ~/api_server
          git pull
          source ~/miniconda3/bin/activate Py311
          pip install -r requirements.txt
          sudo systemctl restart fastapi
